### PR TITLE
grammar: Escape ampersands

### PR DESCRIPTION
**Pull request by vmg**
Hey there! As you may know, we use this JSyntax package to provide syntax highlighting for J files in GitHub.

I'm currently working on improving the way we load and perform syntax highlighting on the website, and I've noticed that there's an issue in the existing grammar which is chocking our new parser.

Specifically: the `&` character, even when inside a regexp, needs to be escaped as `&amp;`. This is a requirement for XML.

The proposed change fixes the issue in a backwards-compatible way. I'd appreciate if you could merge it. Thank you!

### CODE REVIEW

**Comment by tikkanz** [comment]
Hi vmg,
I've forked this this package and further developed it to significantly extend the the syntax highlighting of J. In addition it now supports the newer [*.sublime-syntax.](http://www.sublimetext.com/docs/3/syntax.html) which includes a test script to validate the specification. I'm not sure if that is of any use to you?
I haven't had any luck getting [these changes](https://github.com/bcj/JSyntax/pull/3) merged though.

**Comment by vmg** [comment]
Hey @tikkanz! It does look like this repository is inactive. If you care to push this commit to your own fork to fix the parsing, I'll gladly switch GitHub to use your fork for syntax highlighting.

**Comment by tikkanz** [comment]
Hi @vmg I don't think the patch is required in [my fork](https://github.com/tikkanz/JSyntax) (i.e. ampersand is already replaced with `&amp;`) in the `J.tmLanguage` file?
The newer `J.sublime-syntax` file doesn't do this, but it is YAML and escaping the ampersands breaks the Sublime Text 3 syntax highlighting.

**Comment by vmg** [comment]
Ah, I gotcha. Your fork is indeed working properly! I'll update `github/linguist` to start using it. The changes should roll out soon.

Thank you!!

**Pull request closed without merging**
